# Generated by Django 4.1.7 on 2023-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
